# Generated by Django 3.1.2 on 2020-11-19 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('StoreApp', '0002_person_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='user_type',
        ),
        migrations.AlterField(
            model_name='person',
            name='group',
            field=models.OneToOneField(blank=True, default=2, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.group'),
        ),
    ]
